# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20161114_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobox',
            options={'verbose_name_plural': 'Infoboxes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.ImageField(upload_to='board/'),
        ),
    ]
