# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20161118_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['view_order']},
        ),
        migrations.AddField(
            model_name='boardmember',
            name='view_order',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
