# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20161118_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='view_order',
            field=models.IntegerField(default=1),
        ),
    ]
