# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20161118_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['role']},
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='view_order',
        ),
    ]
