# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20161118_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.IntegerField(choices=[('Puheenjohtaja', 'Puheenjohtaja'), ('Varapuheenjohtaja', 'Varapuheenjohtaja'), ('Rahastonhoitaja', 'Rahastonhoitaja'), ('Sihteeri', 'Sihteeri'), ('Tiedotus- ja fuksivastaava', 'Tiedotus- ja fuksivastaava'), ('Liikunta- ja huvivastaava', 'Liikunta- ja huvivastaava'), ('Isäntä', 'Isäntä'), ('Emäntä', 'Emäntä'), ('Varajäsen', 'Varajäsen'), ('Toimari', 'Toimari'), ('Kooraaja', 'Kooraaja')]),
        ),
    ]
