# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20161118_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['view_order']},
        ),
        migrations.AddField(
            model_name='boardmember',
            name='view_order',
            field=models.IntegerField(choices=[(1, 'Puheenjohtaja'), (2, 'Varapuheenjohtaja'), (3, 'Rahastonhoitaja'), (4, 'Sihteeri'), (5, 'Tiedotus- ja fuksivastaava'), (6, 'Liikunta- ja huvivastaava'), (7, 'Isäntä'), (8, 'Emäntä'), (9, 'Varajäsen'), (10, 'Toimari'), (11, 'Kooraaja')], default=1),
            preserve_default=False,
        ),
    ]
