# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0011_auto_20161118_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infobox',
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='ircnick',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
